name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21.x', '1.22.x']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version:  ${{ matrix.go-version }}
    - name: Build
      run: go build -v ./...
    - name: Format Check
      run: test $(gofmt -l . | wc -l) -eq 0 || exit 1
    - name: Test
      run: go test -v ./...
